[env:teensy41]
platform = platformio/teensy@5.2.0
board = teensy41
framework = arduino
build_flags = -I core -I teensy -DUSB_MIDI_AUDIO_SERIAL -DUSB_MIDI -DUSB_AUDIO
lib_deps = bblanchon/ArduinoJson@^6.19.4
board_build.usbtype = USB_MIDI_AUDIO_SERIAL

; If you prefer a conventional layout, move `CookieBox.ino` into `src/main.ino` and remove `src_dir` from the ini.

[platformio]
src_dir = .
